import './globals.css';
import { Inter } from 'next/font/google';
import ClerkProvider from '@/Provider/ClerkProvider';
import { ThemeProvider } from '@/Provider/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Crypto Trading Bot',
    description: 'Generated by Crypto Trading Bot'
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang='en' suppressHydrationWarning>
                <body>
                    <ThemeProvider attribute='class' defaultTheme='dark' disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
